project:
  type: website
  output-dir: docs

website:
  title: "STAT 412"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: schedule.qmd
        text: Schedule
      - href: handouts.qmd
        text: Handouts
      - href: case_study.qmd
        text: Case Studies

format:
  html:
    theme: flatly
    backgroundcolor: '#f7eedf'
    linkcolor: '#785a3b'
    toc: false
    code-block-bg: '#f5f5f5'

editor: visual

