project:
  type: website
  output-dir: docs

website:
  title: "STAT 412"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: schedule.qmd
        text: Schedule
      - href: handouts.qmd
        text: Handouts

format:
  html:
    theme: flatly
    backgroundcolor: '#f5f0e9'
    linkcolor: '#6d423a'
    toc: false

editor: visual

