---
title: "Case studies"
format: 
  html:
    css: styles.css
---

## Case study 2

Your second case study will once again be performed in pairs of Becky's choosing! Each group will submit 1 report in the form of both a `.Rmd` (or `.qmd`) and a knitted/rendered PDF. These will be submitted to Canvas (not in-person) by Wednesday, 11/12 at 11:59pm.

**I anticipate you will run into questions/concerns – this is good. Don't hesitate to come ask Becky!**

The description of the case study and the data are found here:

-   [Description](case_study/federalist_description.pdf)

-   Data: {{< downloadthis case_study/federalist_papers.csv dname="federalist_papers" label="federalist_papers" id=mtcars-btn >}}

-   Optional `.Rmd` template: {{< downloadthis case_study/case_study_2_template.Rmd dname="caseStudy2" label="caseStudy2" id=mtcars-btn >}}

------------------------------------------------------------------------

## Case study 1

Your first case study will be performed in pairs! You should work together; don't just divy up the work. A large part of modeling is bouncing ideas back and forth and checking in to make sure things "make sense". Each group will submit 1 report in the form of both a `.Rmd` and a knitted/rendered PDF. These will be submitted to Canvas (not in-person) by beginning of class 10/15.

The description of the case study and the data are found here:

-   [Description](case_study/marriage_rates_description.pdf)

-   Data: {{< downloadthis case_study/ItalyMarriageRates.csv dname="ItalyMarriageRates" label="ItalyMarriageRates" id=mtcars-btn >}}

-   Optional `.Rmd` template: {{< downloadthis case_study/case_study_1_template.Rmd dname="caseStudy1" label="caseStudy1" id=mtcars-btn >}}

#### **Presentation**

-   Each group will give a brief 5 minute presentation of their work to the class on 10/15. Presentation order will be randomized.

-   Your presentation should be accompanied by a *brief* set of slides. As we are all aware of the data, these slides should focus mostly on describing your statistical model and how you arrived at it, as well as results (with interpretation).

    -   Think about embedding LaTex equations and R plots for your statistical model. These should be presented in an *effective* manner.

    -   Your presentation of results should answer the research question in an *effective* manner. Does that mean you'll present a table of posterior summary quantities, a plot of a posterior density, or something else?

-   You should be prepared to answer questions from the audience. You should also be prepared to ask questions of presenters.

-   You *don't* need to submit your slides for this case study! Just be prepared to present from a laptop!

-   This presentation is worth 5 points, in addition to the 35 points of the written portion. However, the presentation will be graded on an individual basis, rather than the entire group. A **general rubric** is:

    -   1 point: slides *effectively* share statistical model.
    -   1 point: slides *effectively* share results that answer the research question(s)
    -   1 point: speaker appears practiced and shares speaking time.
        -   "Appearing practiced" also encompasses being as close to the 5-minute duration as possible!
        -   Because this presentation is short and you're so close to your model, you shouldn't be reading off any sort of notes!
    -   1 point: speaker is able to thoughtfully answer questions from audience
    -   1 point: asks at least one interesting/thoughtful/relevant question to other speakers

-   "Effective" is a broad term that I use to cover:

    -   Presenting equations/distributions/slides in a logical order
    -   Having font (both text and on figures/tables) be large enough for the audience to see
    -   Slides have enough text to be generally understood without a speaker, but each slide's content is elevated/made complete by the speaker's additions/commentary
    -   Minimal errors in terms of spelling and typesetting
