---
title: "STAT 412: Bayesian Statistics"
---

Welcome to the website for Middlebury College’s Fall 2025 STAT 412. On this website you will find the course syllabus, schedule, and assignments. The website is frequently updated throughout the semester, so please make a habit of refreshing the page.

## Announcements

-   Midterm revisions due Friday 10/24 at 5pm (leave in box outside office or hand in directly)

    -   Problems 2 and 4 are eligible for revision: on a separate sheet of paper, please re-do the problem parts you're revising in their entirety (e.g. all of part (a) or part (b), even if you only made a mistake towards the end). Attach revisions to original midterm.

    -   Please don't consult any resource beside your notes and Becky!!

## Course details

**Instructor**: Becky Tang (she/her)

-   Office: WNS 214

-   Email: btang\@middlebury.edu

**Meeting times and location**: Mondays and Wednesdays 9:45-11am in WNS 011

**Office hours**: Monday 3-4pm, Tuesday 3:30-4:30pm, Friday 11am-12pm

**Syllabus** (most recent update 9/1/2025): our [syllabus](stat412_syllabus.pdf) outlines our course policies and a rough schedule. Once classes begin, you should follow the schedule and due dates found on this website.
