---
title: "Schedule"
---

*This page is frequently updated!*

+--------+---------+-------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Week   | Date    | Topic                                                                                           | Assignments                                                                                                                                                                                                                                         |
+:======:+:=======:+=================================================================================================+=====================================================================================================================================================================================================================================================+
| **1**  | M 9/08  | -   Welcome!                                                                                    | -   [Problem Set 0](homework/review.pdf) (due next class 9/10)                                                                                                                                                                                      |
|        |         | -   What is a statistical model?                                                                |                                                                                                                                                                                                                                                     |
+--------+---------+-------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|        | W 9/10  | -   Bayes' rule, Bayes modeling                                                                 | -   [Problem Set 1](homework/412_hw1.pdf) (due next class 9/15)                                                                                                                                                                                     |
|        |         |     -   Likelihood, prior, posterior                                                            |                                                                                                                                                                                                                                                     |
|        |         |     -   [Code](code/binom_discrete_prior.qmd) and [worksheet](handouts/binom_prob_discrete.pdf) |                                                                                                                                                                                                                                                     |
+--------+---------+-------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **2**  | M 9/15  | -   Beta-Binomial model                                                                         | -   [Problem Set 2](homework/412_hw2.pdf) (due 9/24)                                                                                                                                                                                                |
|        |         |     -   [Proportionality](code/proportionality.qmd)                                             |                                                                                                                                                                                                                                                     |
|        |         | -   Posterior predictive distribution                                                           |                                                                                                                                                                                                                                                     |
+--------+---------+-------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|        | W 9/17  | -   Bayes estimators/estimates                                                                  | -   [Problem Set 2](homework/412_hw2.pdf) (due 9/24)                                                                                                                                                                                                |
|        |         |     -   Some [proofs](handouts/bayes_est.qmd)                                                   |                                                                                                                                                                                                                                                     |
+--------+---------+-------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **3**  | M 9/22  | -   Confidence regions                                                                          |                                                                                                                                                                                                                                                     |
|        |         | -   Posterior quantities and posterior predictive checks via simulation                         |                                                                                                                                                                                                                                                     |
|        |         |     -   [Code](code/post_pred_checks.qmd)                                                       |                                                                                                                                                                                                                                                     |
+--------+---------+-------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|        | W 9/24  | -   Conjugacy                                                                                   | -   [Problem Set 3](homework/412_hw3.pdf) (complete!)                                                                                                                                                                                               |
|        |         | -   Normal sampling model                                                                       |                                                                                                                                                                                                                                                     |
|        |         |                                                                                                 |     [Code for HW 3](code/hpd_code.qmd)                                                                                                                                                                                                              |
+--------+---------+-------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **4**  | M 9/29  | -   Markov chain basics                                                                         |                                                                                                                                                                                                                                                     |
+--------+---------+-------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|        | W 10/01 | -   Normal model (cont.) with Gibbs sampling!                                                   | -   For **Monday**, read the article *Explaining the Gibbs Sampler* under Handouts and prepare to discuss!                                                                                                                                          |
|        |         |     -   Data under [Handouts](handouts.qmd)                                                     |                                                                                                                                                                                                                                                     |
|        |         |     -   [Code](code/gibbs_normal_model_walkthrough.qmd) from class                              | -   [Problem Set 4](homework/412_hw4.pdf)                                                                                                                                                                                                           |
+--------+---------+-------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **5**  | M 10/06 | -   Discuss *Explaining the Gibbs Sampler*                                                      |                                                                                                                                                                                                                                                     |
|        |         | -   MCMC diagnostics                                                                            |                                                                                                                                                                                                                                                     |
|        |         |     -   Code [here](code/mixture_normals.qmd)                                                   |                                                                                                                                                                                                                                                     |
+--------+---------+-------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|        | W 10/06 | -   Finish MCMC diagnostics                                                                     | -   Work on [Case Study 1](case_study.qmd)                                                                                                                                                                                                          |
|        |         | -   Jeffrey's prior                                                                             |                                                                                                                                                                                                                                                     |
|        |         | -   Introduce Case Study 1                                                                      |                                                                                                                                                                                                                                                     |
+--------+---------+-------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **6**  | M 10/13 | *Becky out of town; Prof. Christian Stratton will be here in my stead!*                         | -   Work on Case Study 1                                                                                                                                                                                                                            |
|        |         |                                                                                                 |                                                                                                                                                                                                                                                     |
|        |         | -   Work on Case Study 1                                                                        |                                                                                                                                                                                                                                                     |
|        |         | -   Work on midterm review                                                                      |                                                                                                                                                                                                                                                     |
+--------+---------+-------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|        | W 10/15 | -   Present Case Study 1                                                                        | -   Study for midterm!                                                                                                                                                                                                                              |
+--------+---------+-------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **7**  | M 10/20 | -   Bayesian hierarchical modeling                                                              |                                                                                                                                                                                                                                                     |
|        |         |     -   [Handout](code/hierarchical_normal_schools.qmd)                                         |                                                                                                                                                                                                                                                     |
+--------+---------+-------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|        | W 10/22 | -   Bayesian hierarchical modeling (cont.)                                                      | -   [Problem Set 5](homework/412_hw5.pdf)                                                                                                                                                                                                           |
|        |         |     -   Find data on handouts slide                                                             |                                                                                                                                                                                                                                                     |
|        |         |                                                                                                 |     -   Starter template and data under handouts                                                                                                                                                                                                    |
+--------+---------+-------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **8**  | M 10/27 | -   Bayesian simple linear regression                                                           | For Wednesday, please read:                                                                                                                                                                                                                         |
|        |         |     -   [Handout](code/bayes_slr.qmd)                                                           |                                                                                                                                                                                                                                                     |
|        |         |                                                                                                 | -   Section 7.1 of Hoff (pg. 105-7)                                                                                                                                                                                                                 |
|        |         |                                                                                                 |                                                                                                                                                                                                                                                     |
|        |         |                                                                                                 | -   Pg. 337-341 of [Blitzstein & Hwang](https://drive.google.com/file/d/1VmkAAGOYCTORq1wxSQqy255qLJjTNvBI/edit) (stop before Ex. 7.5.8. Skip Definition 7.5.6 and proofs if you'd like! But if you miss MGFs, now's your chance to see them again!) |
+--------+---------+-------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|        | W 10/29 | -   Multiple linear regression                                                                  | -   [Problem Set 6](homework/412_hw6.pdf) (updated 10/31 for clarification on #4)                                                                                                                                                                   |
|        |         |     -   [Handout + code](code/bayes_mlr.qmd)                                                    |                                                                                                                                                                                                                                                     |
+--------+---------+-------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **9**  | M 11/03 | -   Metropolis                                                                                  |                                                                                                                                                                                                                                                     |
|        |         |     -   [Handout](code/metropolis.qmd)                                                          |                                                                                                                                                                                                                                                     |
+--------+---------+-------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|        | W 11/05 | -   Metropolis (cont.)                                                                          |                                                                                                                                                                                                                                                     |
|        |         | -   Introduce Case Study 2                                                                      |                                                                                                                                                                                                                                                     |
+--------+---------+-------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **10** | M 11/10 | -   JAGS                                                                                        |                                                                                                                                                                                                                                                     |
+--------+---------+-------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|        | W 11/12 | -   Case Study 2 presentations                                                                  |                                                                                                                                                                                                                                                     |
|        |         |                                                                                                 |                                                                                                                                                                                                                                                     |
|        |         | -   JAGS (cont.)                                                                                |                                                                                                                                                                                                                                                     |
+--------+---------+-------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **11** | M 11/17 | -   Real-data analysis (ecology!)                                                               |                                                                                                                                                                                                                                                     |
+--------+---------+-------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|        | W 11/19 | -   Introduce Case Study 3                                                                      |                                                                                                                                                                                                                                                     |
+--------+---------+-------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|        |         | THANKSGIVING                                                                                    |                                                                                                                                                                                                                                                     |
+--------+---------+-------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **12** | M 12/01 | -   Introduce final project                                                                     |                                                                                                                                                                                                                                                     |
|        |         |                                                                                                 |                                                                                                                                                                                                                                                     |
|        |         | -   Work on Case Study 3                                                                        |                                                                                                                                                                                                                                                     |
+--------+---------+-------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|        | W 12/03 | -   Case Study 3 presentations                                                                  |                                                                                                                                                                                                                                                     |
|        |         |                                                                                                 |                                                                                                                                                                                                                                                     |
|        |         | -   CRFs                                                                                        |                                                                                                                                                                                                                                                     |
+--------+---------+-------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
